### ISSUE TITLE
AVRSensor is lacking destroy method

### ISSUE THREAD

**Issue by mwittig** [saxn-paule/pimatic-pio-remote#3]
See https://github.com/pimatic/pimatic/issues/859 for details

**Comment by saxn-paule** [comment]
Added destroy method an tested it on a Pi 3 with pimatic 0.9.28 and a VSX-921

Could you please verify, that the plugin is working now.

I pushed the changes to the "develop" branch.

**Comment by mwittig** [comment]
Hi, you need to clear the interval timer which calls the getter repeatedly.

**Comment by saxn-paule** [comment]
Do you mean this lines:

```
return setInterval((function () {
  return getter().then(function (value) {
    return _this.emit(name, value);
  })["catch"](function (error) {
    return env.logger.debug(error.stack);
  });
}), 1000);
```

I request the getter each second to update the display value. Otherwise I couldn't mirror the AVRs display to pimatic.

**Comment by mwittig** [comment]
Well, yes. You need to cancel the interval as part of the destroy method.

**Comment by saxn-paule** [comment]
Added clearTimeout call in destroy method

**Comment by saxn-paule** [comment]
I considered your code in the current version (0.5.2). Thank you.
